---
  - name: Provision an EC2 Instance
    hosts: local
    connection: local
    gather_facts: False
    tags: provisioning
    # Necessary Variables for creating/provisioning the EC2 Instance
    vars:
      AWS_ACCESS_KEY: # Removed due to security reason
      AWS_SECRET_KEY: # Removed due to security reason     
      instance_type: t2.micro
      security_group: Ansible-databaseerverdemo 
      image: ami-0cd3dfa4e37921605 
      keypair: ansible-webserver-demo # This is one of my keys that i already have in AWS
      region: us-east-2 # Change the Region
      count: 1

    # Task that will be used to Launch/Create an EC2 Instance
    tasks:

      - name: Create a security group
        local_action: 
          module: ec2_group
          name: "{{ security_group }}"
          description: Security Group for database Server
          region: "{{ region }}"
          rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 108.170.41.76/32
            - proto: tcp
              from_port: 3306
              to_port: 3306
              cidr_ip: 172.31.0.0/16
          rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
        register: basic_firewall

      - name: Launch the new EC2 Instance
        local_action: ec2 
                      group={{ security_group }} 
                      instance_type={{ instance_type}} 
                      image={{ image }} 
                      wait=true 
                      region={{ region }} 
                      keypair={{ keypair }}
                      count={{count}}
        register: ec2

      - name: Assign elastic IP address to the Instance
        ec2_eip:
                device_id: "{{ item }}"
                region: us-east-2
        with_items: "{{ ec2.instance_ids }}"

      - name: Add tag to Instance(s)
        local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
        with_items: "{{ ec2.instances }}"
        args:
          tags:
            Name: Database
